### ISSUE TITLE
Vertical slider?

### ISSUE THREAD

**Issue by Pitu** [ktsn/vue-range-slider#16]
I was wondering if it's possible to have the slider work vertically. The following css rotates the slider successfully but the knob keeps reacting to horizontal mouse movements instead of vertical ones.
```css
range-slider {
    transform: rotate(-90deg);
}
```
